"""Initial check

Revision ID: e852e7eb2474
Revises: 
Create Date: 2023-12-10 18:19:04.829552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e852e7eb2474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('referrals',
    sa.Column('referral_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id_sender', sa.BigInteger(), nullable=True),
    sa.Column('user_id_invited', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_invited'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_sender'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('referral_id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id_creator', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('bot_token', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id_creator'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id_fk', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('category_title', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id_fk'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('promocodes',
    sa.Column('promocode_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('promocode_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('promocode_id'),
    sa.UniqueConstraint('promocode_id')
    )
    op.create_table('users_store',
    sa.Column('user_store_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_store_id'),
    sa.UniqueConstraint('user_store_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_store_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('payment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_store_id'], ['users_store.user_store_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('product_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('baskets_products',
    sa.Column('baskets_products_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_store_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_store_id'], ['users_store.user_store_id'], ),
    sa.PrimaryKeyConstraint('baskets_products_id'),
    sa.UniqueConstraint('baskets_products_id')
    )
    op.create_table('orders_products',
    sa.Column('orders_products_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('orders_products_id'),
    sa.UniqueConstraint('orders_products_id')
    )
    op.create_table('products_photos',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_photos')
    op.drop_table('orders_products')
    op.drop_table('baskets_products')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users_store')
    op.drop_table('promocodes')
    op.drop_table('categories')
    op.drop_table('stores')
    op.drop_table('referrals')
    op.drop_table('users')
    # ### end Alembic commands ###
